source 'https://rubygems.org'

gem 'mysql2'
gem 'sinatra'
gem 'thin'
gem 'redis'

group :development do
  gem 'sinatra-contrib', require: nil
  gem 'stackprof'
  gem 'dotenv'
  gem 'mysql2-client-general_log', github: 'ABCanG/mysql2-client-general_log', branch: 'writefile'
end
