version: '2'
services:
  react_dev:
    build:
      context: ./react
      dockerfile: Dockerfile-dev
    volumes:
      - ./react:/react
      - /react/node_modules
      - /react/build
    environment:
      ISUCON_ENV: development
      PORT: 80
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    environment:
      ISUCON_ENV: production
      NODE_ENV: production
      PORT: 80
