version: '2'
services:
  ruby:
    build:
      context: ./ruby
      dockerfile: Dockerfile
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
    ports:
      - "443:443"
