version: '2'
services:
  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
  redis:
    restart: always
    image: redis
    command: redis-server --appendonly yes
  ruby:
    build:
      context: ./ruby
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
      REDIS_HOST: redis
      REDIS_PORT: 6379
  react:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - ruby
    links:
      - ruby
    environment:
      API: http://ruby:80
    ports:
      - "443:443"
