version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates/
      - ./ssl:/etc/nginx/ssl/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=443
    ports:
      - "443:443"
    command: /bin/bash -c "envsubst < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx"
